### ISSUE TITLE
Research into VideoAsk API

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#105]
For SP website. 

For the application we want to incorporate using VideoAsk in the form. 
The ideal flow is in the mockup shown below. 

We need to see if their API allows us to intervene and take the user directly from their flow back to our flow when the user has completed the questions and before VideoAsk's 'complete' screen shows up ( See mockup flow for details )

**Comment by anikey** [comment]
[videoask.pdf](https://github.com/commitdev/commit.dev/files/6039888/videoask.pdf)

**Comment by adriandelisle** [comment]
@anikey It definitely looks like both the embedding and showing different component/screen on complete are possible. I created some example code for the person that ends up actually implementing it. (#148)

Videoask has some more examples and API docs [here](https://www.videoask.com/help/embed/advanced-embed-options) for when it comes to actually implementing it.

Here's a video of the example in action.
https://user-images.githubusercontent.com/10035832/110042155-3521ae00-7cfa-11eb-9fcc-641c6bc29e6e.mp4

**Comment by anikey** [comment]
@adriandelisle  Thanks so much for looking into this! Awesome that it's possible! Let's keep #148 open then for whoever gets to working on it?   PS. YOUR CAT IS SO CUTE

**Comment by adriandelisle** [comment]
Closing since the spike is completed
