### ISSUE TITLE
Update commit logo color in hero page

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#108]
The current one is using the old color so we'll need to update the color to be the updated branding color. 

The asset should be in SVG so you can change the color according to the Figma design file otherwise if easier feel free to ping Anita for the svg logo asset.
<img width="1680" alt="commit_logo" src="https://user-images.githubusercontent.com/29130378/109178076-56ecc500-773d-11eb-8263-572925ec50da.png">

**Comment by adriandelisle** [comment]
Done in #120
