### ISSUE TITLE
[Mobile] Update background color of hero section & footer section

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#113]
Update hero section and footer section of mobile to have the same background gradient color as desktop view

**Comment by adriandelisle** [comment]
#106 fixes the hero section, but I'm not sure about the footer

**Comment by adriandelisle** [comment]
Just double checked and #106 updated both the hero and footer sections to have the same background gradient as desktop.
![Screen Shot 2021-02-25 at 2 49 34 PM](https://user-images.githubusercontent.com/10035832/109230294-7acdfc00-7779-11eb-8e67-894123c7fcbc.png)
![Screen Shot 2021-02-25 at 2 49 49 PM](https://user-images.githubusercontent.com/10035832/109230299-7c97bf80-7779-11eb-85f1-468f571f1f84.png)
