### ISSUE TITLE
[MOBILE] Adjust alignment of exec team headshots

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#118]
Headshots of the team should be 2 headshots per line except renee's will be the only one that is alone at the left. 

<img width="421" alt="Screen Shot 2021-02-26 at 8 12 11 AM" src="https://user-images.githubusercontent.com/29130378/109325242-8d444600-780a-11eb-802c-11729c28d1b1.png">
<img width="418" alt="Screen Shot 2021-02-26 at 8 12 22 AM" src="https://user-images.githubusercontent.com/29130378/109325248-8e757300-780a-11eb-948c-44d55f1b6ac5.png">

**Comment by adriandelisle** [comment]
@anikey Around what screen width is this happening?

**Comment by anikey** [comment]
@adriandelisle  small tablet size/breakpoint :  768px

**Comment by adriandelisle** [comment]
Done in #124
