### ISSUE TITLE
Redesign of the application form

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#122]
Please check figma file for the design details
Overall we are moving towards using more squared radius, lower opacity, font styles.
Also confirming that the "Start taking control of your career" title has a 96px line height 

https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1559%3A52

![image](https://user-images.githubusercontent.com/29130378/109352689-0efa9a80-7830-11eb-8385-effbf61e94d5.png)

![image](https://user-images.githubusercontent.com/29130378/109352723-1c178980-7830-11eb-9041-cd7b4f37167f.png)

![image](https://user-images.githubusercontent.com/29130378/109353180-d8714f80-7830-11eb-995f-ce4c5cc3f251.png)

**Comment by adriandelisle** [comment]
Done in #142
