### ISSUE TITLE
[ MOBILE ] Make sure default view of team section in about page is collapsed

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#126]
Make sure that the default on mobile view for the team section is in collapsed view where only Greg and Beier's headshots show with the expand button. Might be an issue on my end but when I land on it in mobile view it shows all the headshots ( let me know if it's an issue on my end)

![image](https://user-images.githubusercontent.com/29130378/109524908-dba15100-7a65-11eb-904d-4e6adde6db11.png)

**Comment by adriandelisle** [comment]
@anikey I fixed the default to be collapsed.
