### ISSUE TITLE
CTA Button design updates

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#127]
1.**Button width** - I've updated the width of the button to have 42px padding left/right of the button and decreasing the width of the text area in the button so overall the button is not as wide ( it felt a bit wide when I was going through designs again )

This will apply to all views except mobile, mobile we will keep as full width still!

2. **Hover interaction** - Please take a look at the figma file and let me know if this is possible! I thought it would be fun to incorporate some type of code aspect to the interaction. Feel free and would love to hear new ideas for a new/better "code" for the button that you think other engineers would find funny/amusing!

![image](https://user-images.githubusercontent.com/29130378/109526206-2bcce300-7a67-11eb-98b3-6e8f4dc0e09d.png)

**Comment by jaydlawrence** [comment]
https://github.com/commitdev/commit.dev/pull/133
