### ISSUE TITLE
Headshots of other members missing in other views except mobile

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#149]
I think this happened after we implemented the expandable view in mobile for the team page, it made it so that only beier and greg's headshot shows for all the other views.
Ideally we want to show all the headshots except for mobile where we just show Beier and Greg's with the option for users to expand to show the whole team. If it's too much work we can ignore the mobile expand option for now.
 <img width="1680" alt="Screen Shot 2021-03-05 at 7 56 49 AM" src="https://user-images.githubusercontent.com/29130378/110141431-ffc4a100-7d89-11eb-9308-5dea7104aaf7.png">

**Comment by adriandelisle** [comment]
Fixed in #151
