### ISSUE TITLE
Add social icons to footer nav

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#161]
Check figma design file for design details

![socialicon](https://user-images.githubusercontent.com/29130378/110399188-3ddff000-802a-11eb-83f4-b87be6b253ea.png)

**Comment by anikey** [comment]
URL

Github  [https://github.com/commitdev](url)
Linkedin [https://www.linkedin.com/company/commitdev/mycompany/](url)
Twitter [https://twitter.com/commitdev?lang=en](url)

**Comment by adriandelisle** [comment]
@anikey This is out now on https://commit-staging.dev/, let me know if there's any issues.

**Comment by anikey** [comment]
@adriandelisle  Link is taking me to the form :/ But I remember seeing the social icons yesterday

![image](https://user-images.githubusercontent.com/29130378/110658316-7096ff00-8176-11eb-88ab-75b97648e92b.png)

**Comment by adriandelisle** [comment]
@anikey its back to launch now. There was a release of the old site that overrode it last night.

**Comment by anikey** [comment]
@adriandelisle  looks good Thanks!!
