### ISSUE TITLE
Implement " faces behind commit.dev " section

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#167]
Please see design details in the figma file

If the scattered headshot view is too complex we can default to having a grid view. I'm thinking this scattered view works well with the context as the website is open source ( many different people coming to pick it up and leave when they get busy )

Placement of the headhshots does not need to be pixel perfect to the design but should look well balanced on the page.

[ https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1889%3A48
 ](url)

![commit dev_minions](https://user-images.githubusercontent.com/29130378/110666751-75f84780-817e-11eb-8bb5-f00c477389f2.png)

**Comment by superkhau** [comment]
Only thing left is to update images with the current dev team. ;)
