### ISSUE TITLE
Make the header/navigation persistent

### ISSUE THREAD

**Issue by adriandelisle** [commitdev/commit.dev-proto#170]
Update the header/navigation to persist at the top of the page when scrolled out of view. Similar to http://clearbanc.com/.

~Design TBD~

**Comment by anikey** [comment]
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1939%3A444

![image](https://user-images.githubusercontent.com/29130378/110901316-020e8a00-82b9-11eb-80fc-b5ec63bcf1bf.png)

**Comment by adriandelisle** [comment]
@anikey I have I PR to update the header to the design: #172. With the background being transparent I found it a bit hard to see the header at times. Should it be updated to a solid colour?

Transparent background:
![ezgif-6-6986d19c0e91](https://user-images.githubusercontent.com/10035832/110986911-24d58880-8323-11eb-8070-f4fcefc5859d.gif)
![ezgif-6-133a6db2575e](https://user-images.githubusercontent.com/10035832/110986919-269f4c00-8323-11eb-8595-967e794bff47.gif)

Solid background:
![ezgif-6-6cd0d1b81928](https://user-images.githubusercontent.com/10035832/110986944-361e9500-8323-11eb-8b80-e494d8ae91e9.gif)

**Comment by anikey** [comment]
DESIGN UPDATE: Let's do a 50% opacity rather than 25%

**Comment by adriandelisle** [comment]
@anikey the persistent header is now on https://commit-staging.dev/

**Comment by anikey** [comment]
Thanks @adriandelisle  Are we able to keep our old header ( white text on our dark gradient bg ) in the beginning and have the persistent style happen when the user starts scrolling? Doesn't have to be done by you- I can create another ticket for someone else to work on it if it is possible )

**Comment by adriandelisle** [comment]
I think that should be possible.

**Comment by anikey** [comment]
Have made a new issue [https://github.com/commitdev/commit.dev/issues/193](url) to address the change discussed

**Comment by alebiavati** [comment]
@adriandelisle @anikey  Created #198 to address the change

**Comment by alebiavati** [comment]
@anikey  @adriandelisle while working on #198 I also discovered that on small screens when you open the hamburger menu the current scroll position is set to the top of the page, so when the menu is closed the user sees the top of the current page instead of their previous scroll position. Should I open a new issue to fix that?

**Comment by anikey** [comment]
@alebiavati  yes please!

**Comment by alebiavati** [comment]
@anikey done! #200
