### ISSUE TITLE
What resources have you seen prior to applying?

### ISSUE THREAD

**Issue by superkhau** [commitdev/commit.dev-proto#175]
Add a question field to the form to capture the question above. The type of field needs to be determined, but possible answers are:

```
Blog, LinkedIn company page, network connection post on LinkedIn, twitter, youtube, word of mouth, event.
```

@anikey You can figure out what field type (whether it's a dropdown or freeform text) is required for this issue with the rest of the stakeholders.

**Comment by superkhau** [comment]
Ping @timothy-wan or @julie-huang too to figure out how to hook it up with our current server setup.

**Comment by anikey** [comment]
![image](https://user-images.githubusercontent.com/29130378/112914093-f93af800-90af-11eb-8cab-08e7bd7d2b2e.png)

![image](https://user-images.githubusercontent.com/29130378/112914756-ae21e480-90b1-11eb-8f90-ccadd03048c9.png)

**Comment by anikey** [comment]
Please refer to figma link for design details
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1559%3A52

**Comment by anikey** [comment]
- Allow users to be able to select more than one resource
- The answers need to be then filled to our spreadsheet ( Ping Tim & Julie on this )
