### ISSUE TITLE
Update Hero Section

### ISSUE THREAD

**Issue by superkhau** [commitdev/commit.dev-proto#176]
Please check figma file for design details

https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=2161%3A565

*** DO NOT IMPLEMENT THE LAST CHOWN CODE LINE - this will be added as a typewriter animation ( in issue 178 [https://github.com/commitdev/commit.dev/issues/178](url). )

It would be best for whoever picks up this ticket to do issue 178 after

![image](https://user-images.githubusercontent.com/29130378/113045574-deba5a80-9153-11eb-8391-0651d7ded7d5.png)

**Comment by anikey** [comment]
@chrisnottca 

Let's remove the bracket graphic on the right and have the "Until now, your growth was dependent on your company"  text be white

Let's have the chown line be the same text size as the text above , I just updated the figma file( last min update )
and then have the subtext be all the same text weight

![image](https://user-images.githubusercontent.com/29130378/113625830-48d07500-9616-11eb-8c8c-4a0d2efd7f79.png)
