### ISSUE TITLE
Create how it works section

### ISSUE THREAD

**Issue by superkhau** [commitdev/commit.dev-proto#180]
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=2183%3A719

This layout uses the same 3 column grid as the section below ( featured articles ) the tablet and mobile layout as well follows the same as our current featured articles section

![image](https://user-images.githubusercontent.com/29130378/113214452-5d83c600-922e-11eb-8242-a72dc72c5135.png)

**Comment by chrisnottca** [comment]
@anikey Item 3 shouldn't have the same title as item 1, right?

**Comment by anikey** [comment]
@chrisnottca  good catch, #3 is join a startup
