### ISSUE TITLE
Update startups section

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#188]
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=2183%3A719

Please check desktop/tablet/mobile view

**Please ping Anita for company logos

OLD : 

![image](https://user-images.githubusercontent.com/29130378/113215378-9d977880-922f-11eb-842e-bff77d45e276.png)

NEW: 

![image](https://user-images.githubusercontent.com/29130378/113215411-a7b97700-922f-11eb-9cdf-1e3a224ef385.png)

**Comment by anikey** [comment]
@Alexandre-Georges  This section looks good! Let's move this section to the top right after  ' we do what's right for the engineer'  section 

![image](https://user-images.githubusercontent.com/29130378/114122819-ef7e7500-98a5-11eb-8e3e-2978153698ff.png)

**Comment by anikey** [comment]
small bug - went on the about page and found that the text/design has changed ( looks like it replicated the home startups section )

![image](https://user-images.githubusercontent.com/29130378/114123140-9236f380-98a6-11eb-9d79-2a181c93d3a1.png)

**Comment by Alexandre-Georges** [comment]
Good catch, the component is reused on both page. That's why I am not a fan of reusing components for styling purposes, the layout or design can change for one of the cases and the component is not reusable anymore.

I will refactor that.

**Comment by Alexandre-Georges** [comment]
The regression has been addressed. It should be good to go now!
