### ISSUE TITLE
Header - Revision

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#193]
This is ongoing work from issue 170 [https://github.com/commitdev/commit.dev/issues/170](url)

Currently the live site header looks like this after implementing the persistent header : 

![image](https://user-images.githubusercontent.com/29130378/113356118-a8691080-92f6-11eb-9e9d-b4b33afe4b07.png)

We want the header to be the old version ( white text on dark gradient bg )when the user lands on the page but once the user scrolls, have the header be the persistent header style

![image](https://user-images.githubusercontent.com/29130378/113359358-778bda00-92fc-11eb-8bf5-b8f646c10d6a.png)

Persistent header style stays as is ( as implemented )
![image](https://user-images.githubusercontent.com/29130378/113359819-6c857980-92fd-11eb-8b88-c4c11f2ed6ed.png)

Keep in mind the about page header stays the same ( dark blue on white )
![image](https://user-images.githubusercontent.com/29130378/113360125-03eacc80-92fe-11eb-9093-7fc357e69c0a.png)

**Comment by alebiavati** [comment]
Hi @anikey, I am working on this ticket and was wondering, apart from the background and text colors, what else changes on the header?
- from the screenshot you provided it looks like the original header has larger vertical paddings, correct?
- does the logo size change when scrolling the page?
- what kind of animation would you like here? I'm using 200 ms animation with ease in & out
- anything else?

This is what I have currently:
![Apr-05-2021 13-38-47](https://user-images.githubusercontent.com/832191/113624319-5553ce00-9614-11eb-9acd-2ed5212c90bf.gif)

**Comment by anikey** [comment]
@alebiavati  The current padding is the same as the old version, I just screenshot in more from the screen - good observation 👍 , logo size does not change when page scrolling. Everything else stays the same
