### ISSUE TITLE
Button hover update revision

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#197]
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=2363%3A30

Please note:
Button width and text size remains the same as default button

OLD:
![image](https://user-images.githubusercontent.com/29130378/113625430-c8aa0f80-9615-11eb-8e5b-97ed8ee97652.png)

REVISED:
![image](https://user-images.githubusercontent.com/29130378/113625453-cf388700-9615-11eb-8fe9-610286014d36.png)

**Comment by Alexandre-Georges** [comment]
The work required in this ticket has already been done. Moving the ticket to done.
