### ISSUE TITLE
Add dev headshots to include the current EPs that are working on the commit.dev site :)

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#212]
Replace Simon, Ashley, and Anita's headshots with Chris Nott, Alessandro Biavati, Alexandre Georges, Andrew Lukonin

![image](https://user-images.githubusercontent.com/29130378/114123562-68320100-98a7-11eb-8ac4-0a52fcd0eca2.png)

**Comment by alebiavati** [comment]
@ALukonin @chrisnottca @Alexandre-Georges could you please send me your headshots? :)
