### ISSUE TITLE
Home > How it works > Responsive grid broken around 640px

### ISSUE THREAD

**Issue by alebiavati** [commitdev/commit.dev-proto#227]
### Description

Home > How it works > Responsive grid broken around 640px

### Context

- **Browser**:  all
- **OS**: all

### Steps to Reproduce

1. Visit https://launch.commit-staging.dev/
1. Scroll to How it Works section
1. Change browser width to ~640px

**Expected behavior:** 
Blocks should fit in page

**Actual behavior:** 
- Blocks break over 2 rows
- Titles are not center aligned

### Additional context / Screenshots

![Screen Shot 2021-04-09 at 3 01 47 PM](https://user-images.githubusercontent.com/832191/114245132-b47f4e80-9944-11eb-8501-380dba7f0965.png)

**Comment by chrisnottca** [comment]
Fixed by PR 231

**Comment by alebiavati** [comment]
@chrisnottca  Thanks! closing
