### ISSUE TITLE
[Firefox] Home hero prevents page scrolling

### ISSUE THREAD

**Issue by alebiavati** [commitdev/commit.dev-proto#236]
### Description

The hero section contains a scrollable area that "traps" the user from scrolling the rest of the page.

### Context

- **Browser**:  Firefox v87.0
- **OS**: macOS v11.2.3

### Steps to Reproduce

1. Visit https://commit-staging.dev/
1. Try to scroll when mouse is over the hero area (see screenshot)

**Expected behavior:** 
Page scrolls normally

**Actual behavior:** 
Only hero section content scrolls for just 10px or so, while page stays scrolled to the top.

### Possible Solution

Make section not scrollable by removing height constraints or adding overflow hidden.

### Additional context / Screenshots

![Screen Shot 2021-04-12 at 1 09 21 PM](https://user-images.githubusercontent.com/832191/114456111-56937680-9b91-11eb-8034-612bce4b9b6a.png)

**Comment by chrisnottca** [comment]
I believe this got fixed when I redid some of the hero styles while fixing the typing animation

**Comment by alebiavati** [comment]
yep!
