### ISSUE TITLE
Select placeholder color too light

### ISSUE THREAD

**Issue by alebiavati** [commitdev/commit.dev-proto#237]
### Description

Select placeholder color too light

### Context

- **Browser**:  any
- **OS**: any

### Steps to Reproduce

1. Visit https://commit-staging.dev
1. Click apply button

**Expected behavior:** 
Select placeholder should be the same color as other fields

**Actual behavior:** 
Select placeholder is too light

### Additional context / Screenshots

![Screen Shot 2021-04-12 at 1 25 50 PM](https://user-images.githubusercontent.com/832191/114457951-76c43500-9b93-11eb-8d13-4c37cf26c717.png)

**Comment by ALukonin** [comment]
Completed with apply page mobile bug fix. Issue: https://github.com/commitdev/commit.dev/issues/243, PR: https://github.com/commitdev/commit.dev/pull/256
