### ISSUE TITLE
Application form does not have any field validation

### ISSUE THREAD

**Issue by alebiavati** [commitdev/commit.dev-proto#241]
### Description

Application form fields are not being validated on the front-end.
- Name should be required
- Email should be required and should be of "email" type (right now form submits successfully even with just "test" as the email)

### Context

- **Browser**:  any
- **OS**: any

### Steps to Reproduce

1. Visit https://commit-staging.dev/apply

- Submit form without filling anything
- Submit with "test" for every field

**Expected behavior:** 
User can see validation errors

**Actual behavior:** 
Form is submitted to the server

**Comment by ALukonin** [comment]
I can take this on, its something I wanted to do and take on the server side as well. I didn't notice serer side input validation either

**Comment by anikey** [comment]
[https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1059%3A1242](url)

Please go into the 'ep-pre-launch_design' tab on the left side and you'll see the error handling designs. 
Please ignore the application as that was the old design but how the error msg should be displayed still remains the same

![image](https://user-images.githubusercontent.com/29130378/115263449-4a0ba280-a0ea-11eb-974e-fdc8c2123cd2.png)
