### ISSUE TITLE
Timeline design for mobile

### ISSUE THREAD

**Issue by alebiavati** [commitdev/commit.dev-proto#242]
### Description

Timeline section designs for mobile

### Steps to Reproduce

1. Visit https://commit-staging.dev/
1. Scroll to timeline section

**Expected behavior:** 
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=2170%3A502
![Screen Shot 2021-04-12 at 2 06 55 PM](https://user-images.githubusercontent.com/832191/114462785-5f3b7b00-9b98-11eb-90ca-76f3a18aecef.png)

**Actual behavior:** 
![Screen Shot 2021-04-12 at 2 05 10 PM](https://user-images.githubusercontent.com/832191/114462841-78dcc280-9b98-11eb-94b8-1d49b87c1219.png)

**Comment by chrisnottca** [comment]
Subset of https://github.com/commitdev/commit.dev/issues/252 so technically a dup (though 252 was later)
