### ISSUE TITLE
[mobile] Incorrect layout of last Executive Team avatar for odd number of team members

### ISSUE THREAD

**Issue by chrisnottca** [commitdev/commit.dev-proto#245]
### Description

About page: Our Executive Team
If there is an odd number of avatar images, at mobile resolutions, the last avatar is left-aligned and the "Collapse" button appears to its right.

### Context

- Chrome v89.0.4389.105 on Android v9 (Lenova Moto G6)
- Chrome v89.0.4389.90 on MacOS 11.2.2

### Steps to Reproduce

1. Visit https://commit-staging.dev/ on a mobile device or at a viewport width below 390px
2. Go to About screen and scroll to Our Executive Team
3. Click "Whole Team" to view all team members and scroll to the bottom of the list of team members.

**Expected behavior:** 
The last avatar image is centered if it appears by itself on a line and the "Collapse" link appears below it.

**Actual behavior:** 
The last avatar is left-aligned and the "Collapse" button appears to its right.

### Possible Solution

Make last item span the whole width if it is the last one.

### Additional context / Screenshots

![Screenshot_20210412-140708](https://user-images.githubusercontent.com/18448266/114465269-bc84fb80-9b9b-11eb-9857-61fef349cabb.png)

**Comment by alebiavati** [comment]
@chrisnottca This is actually not a bug, it's from the designs:
![Screen Shot 2021-04-12 at 3 32 07 PM](https://user-images.githubusercontent.com/832191/114470762-48028a80-9ba4-11eb-8d78-8e54a74c989e.png)
