### ISSUE TITLE
[ MOBILE ] UI updates to light blue sections

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#255]
![Frame 854](https://user-images.githubusercontent.com/29130378/114479117-a9caf080-9bb4-11eb-9805-3f5e9c6d86ad.png)

**Comment by alebiavati** [comment]
Went through the designs and found these heading styles:

1. Home > Hero: Mon 800 48/1.2 Lower (ls 0%)
2. Home > Do what's right: Mon 800 48/1.58 CAPS (ls 5%)
3. Home > Startup Partners: Mon 400 36/1.5 Lower (ls 5%)
4. Home > How it works: Mon 800 36/1.2 CAPS (ls 10%)
5. Home > How it works subtitle: Mon 800 24/1.2 CAPS (ls 10%)
6. Home > Featured articles: (same as #4)
7. Home > The commit platform: Mon 800 48/1.2 CAPS (ls 10%) (background gradiant)
8. Home > The commit platform subtitle: (same as #5)
9. Home > Engineers who joined: (same as #3)
10. Home > Testimonials: (same as #4)
11. Home > Let's get started: (same as #4)
12. Apply > form hero: Mon 800 64/1.5 Lower (ls 0%)
13. About > hero: Mon 800 64/1.2 Lower (ls 0%)
14. About > Diversity: (same as #4)
15. About > Leadership team: (same as #4)
16. About > Our Software Engineers: (same as #4)
17. About > Open source: Mon 800 36/1.5 CAPS (ls 10%)

So in total there are 9 different heading styles. @anikey maybe we can adjust this list and make it a bit more consistent across? let's chat offline

**Comment by alebiavati** [comment]
I was able to distill down the following reusable Heading styles:

- HeroHeading: Mon 800 64/1.2 Lower (ls 0%)
- SectionHeading: Mon 400 36/1.5 Lower (ls 5%)
- SectionHeadingBold: Mon 800 36/1.2 CAPS (ls 10%)
- SubHeading: SectionHeadingBold, 24px

All other headings can be created using the above reusable styles:

1. Home > Hero: HeroHeading, 48px
2. Home > Do what's right: SectionHeadingBold, 48/1.58 (ls 5%)
3. Home > Startup Partners: SectionHeading
4. Home > How it works: SectionHeadingBold
5. Home > How it works subtitle: SubHeading
6. Home > Featured articles: SectionHeadingBold
7. Home > The commit platform: SectionHeadingBold, 48px (background gradiant)
8. Home > The commit platform subtitle: SubHeading
9. Home > Engineers who joined: SectionHeading
10. Home > Testimonials: SectionHeadingBold
11. Home > Let's get started: SectionHeadingBold
12. Apply > form hero: HeroHeading
13. About > hero: HeroHeading, 1.5lh
14. About > Diversity: SectionHeadingBold
15. About > Leadership team: SectionHeadingBold
16. About > Our Software Engineers: SectionHeadingBold
17. About > Open source: SectionHeadingBold, 1.5lh
