### ISSUE TITLE
Setup PR Template

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#27]
Would be useful to have a template for PRs made against this repo. Since this repo will have various contributors over time, a PR template can help keep things a little more consistent and help guide people on what info is good to include in a PR description.

**Comment by superkhau** [comment]
+1

**Comment by jasondippel** [comment]
This is bugging me so I'll tackle it tomorrow

**Comment by jasondippel** [comment]
Template has been merged. Closing this issue.
