### ISSUE TITLE
[ MOBILE ] Lower 'About' page header text 

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#280]
Let's lower the text a bit so it doesn't fight with the header 

live:
![image](https://user-images.githubusercontent.com/29130378/114812673-4b913f80-9d65-11eb-9e39-d8a47bda2b97.png)

design:
![image](https://user-images.githubusercontent.com/29130378/114812682-54821100-9d65-11eb-93e1-0041efae7420.png)

**Comment by chrisnottca** [comment]
Handled by https://github.com/commitdev/commit.dev/pull/283
