### ISSUE TITLE
Android Chrome - the application form's multiselect field is hard to use on mobile

### ISSUE THREAD

**Issue by robyn3choi** [commitdev/commit.dev-proto#294]
### Description

- When using the multiselect field, the phone's keyboard will show up, even though there isn't really a reason to type.
- Also, after selecting one item, it exits out of the list of items instead of keeping the list open to select more items

https://user-images.githubusercontent.com/9066587/115297760-6f5fd700-a111-11eb-8d10-5dc84d89bc04.mp4

### Context

- Chrome v90.0.4430.66
- Samsung Galaxy S7

**Comment by robyn3choi** [comment]
Should we disable the ability to type into this field? Typing doesn't really serve a purpose right now since there aren't that many items to choose from. This way, the keyboard won't keep showing up when trying to select items.

**Comment by superkhau** [comment]
@robyn3choi Yes, keep it simple and disable it because that is pretty annoying. ;p
