### ISSUE TITLE
Building the new Marketing Site

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#47]
> If you're looking for something to work on, please look through the other issues. This issue is temporary documentation and does not outline work that needs to be done (this will be recorded in other issues)

This issue is meant to help inform people of how the new marketing site is being built out and any gotchas or special considerations to take into account when working on it. Anything in this issue that is relevant to know after the new site has been launched will be added to documentation in the repo (ie not left in this issue).

## Where is this work being done?

While the new site is being developed, we'd like to prevent releasing it onto the commit.dev domain. To do this, we have created a new branch called [launch]() that we are treating as the main branch. Here we will stage all the changes and then, once it is ready to release, we will merge this branch into the main branch.

This means that if you're working on changes for the new marketing site, please ensure PRs that you create are against this `launch` branch rather than the current `main` branch. You can adjust this when creating the PR by selecting the `launch` branch as the base.
<img width="395" alt="Screen Shot 2021-01-29 at 10 42 14 AM" src="https://user-images.githubusercontent.com/5143561/106314621-d5c60f00-621e-11eb-9557-6453fb1d47bb.png">

**Comment by superkhau** [comment]
@jasondippel Should we put this in the Wiki instead? Like a introduction/getting started section? Since this isn't really resolvable, it doesn't really warrant it's own issue IMO.

**Comment by jasondippel** [comment]
I thought about that but wasn't sure, so created this issue in the mean time and to discuss where this should live 😛 

I was hesitant about adding it to a common "Getting Started" section since this is a bit of a special situation for the time being. I was thinking the "Getting Started" section could have an aside or special note at the top saying something like:

## Getting Started

> To contribute to the new marketing site, please read [this issue](https://github.com/commitdev/commit.dev/issues/47) which explains how to contribute. This is temporary and will no longer be required once the new marketing site is released on [commit.dev](https://commit.dev).

...rest of getting started instructions...

**Comment by jasondippel** [comment]
I suppose a middle ground would be to have a separate markdown file somewhere that details this (assuming we don't want to keep this issue and we don't want to add it to the main "Getting Started" section which I'm assuming would live in the main README.md)

**Comment by jasondippel** [comment]
I'm cool with anything though, just wanted to share my thoughts. Would like to hear from @julie-huang and @timothy-wan as well if they have opinions.

**Comment by superkhau** [comment]
I think the wiki makes more sense for this -- How to contribute section. I don't want to put all the instructions in the readme. You can however add a link to the Contribution guide in the readme.

**Comment by jasondippel** [comment]
Moved this info into the contribution guide. Closing.
