### ISSUE TITLE
[Launch] Adjust hero section styles

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#70]
> This work pertains to the new marketing site that is being built on the [launch](https://github.com/commitdev/commit.dev/tree/launch) branch. To learn more about contributing to this work, please see the [contributing guide](https://github.com/commitdev/commit.dev/blob/main/CONTRIBUTING.md)

The hero section of the /about page needs it's styles adjusted to match the designs in figma. The current styling is basically just a copy of what the home page has and likely needs a couple adjustments to get it to match the designs (for all screen sizes).

Figma link: https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1392%3A1524

**Comment by adriandelisle** [comment]
Done in #102
