### ISSUE TITLE
[Launch] Add "Diversity & Inclusion" section to /about page

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#71]
> This work pertains to the new marketing site that is being built on the [launch](https://github.com/commitdev/commit.dev/tree/launch) branch. To learn more about contributing to this work, please see the [contributing guide](https://github.com/commitdev/commit.dev/blob/main/CONTRIBUTING.md)

Need to add the "Diversity & Inclusion" section to the /about page.

Figma Link: https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1392%3A1524

**Comment by adriandelisle** [comment]
Done in #96
