### ISSUE TITLE
[Launch] Adjust styling of mobile overlay nav menu

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#74]
> This work pertains to the new marketing site that is being built on the [launch](https://github.com/commitdev/commit.dev/tree/launch) branch. To learn more about contributing to this work, please see the [contributing guide](https://github.com/commitdev/commit.dev/blob/main/CONTRIBUTING.md)

The styling of the overlay nav that shows up on smaller screens needs some updates to match the new designs.

Figma Link: https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1392%3A1910

**Comment by jaydlawrence** [comment]
https://github.com/commitdev/commit.dev/pull/106
