### ISSUE TITLE
[Launch] Need link back to home page (ie index route)

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#75]
> This work pertains to the new marketing site that is being built on the [launch](https://github.com/commitdev/commit.dev/tree/launch) branch. To learn more about contributing to this work, please see the [contributing guide](https://github.com/commitdev/commit.dev/blob/main/CONTRIBUTING.md)

Right now, once a user navigates away from the home page, there is no link to take them back. This should be added. My guess is that the Commit logo in the site header should become that link, but this should be confirmed with design.

**Comment by adriandelisle** [comment]
Link added in #77
