### ISSUE TITLE
[Launch] Wire up "Apply to Join Us" link

### ISSUE THREAD

**Issue by jasondippel** [commitdev/commit.dev-proto#76]
> This work pertains to the new marketing site that is being built on the [launch](https://github.com/commitdev/commit.dev/tree/launch) branch. To learn more about contributing to this work, please see the [contributing guide](https://github.com/commitdev/commit.dev/blob/main/CONTRIBUTING.md)

> For now, this ticket is more of a place holder until questions below are answered. Currently not in a state where development can work on this.

Right now, the "Apply to Join Us" link in the hero section of the home page and in the footer component does not do anything. Where exactly it should go (or what it should do) should be figured out and then implemented.

**Comment by anikey** [comment]
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1559%3A52 

When a user clicks on the 'apply to Join Us' button it will lead them to the application form similar to the pre-launch application. Note the updated style changes. The form is set to be no wider than 480px

**Comment by adriandelisle** [comment]
Done in #103
