### ISSUE TITLE
Change turquoise highlite. text to blue gradient

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#89]
![cover](https://user-images.githubusercontent.com/29130378/108388818-e0dbe180-71c3-11eb-9265-d57a9936a84f.png)

Change turquoise color highlite text to gradient  

See Figma design for gradient color

https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1202%3A1125

**Comment by adriandelisle** [comment]
Done in #97
