### ISSUE TITLE
Spacing/sizing adjustment of the first 2 blocks on the site

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#90]
![intro](https://user-images.githubusercontent.com/29130378/108389558-a3c41f00-71c4-11eb-9b37-370b837b0515.png)
![aarticles](https://user-images.githubusercontent.com/29130378/108389581-a7f03c80-71c4-11eb-9850-ce16f9bdb511.png)

Update:
1. Spacing between the 3 blocks - too narrow
2. Size of the 3 blocks - too wide
( In current design :  72px spacing between blocks  )

https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1202%3A1125

**Comment by adriandelisle** [comment]
Done in #101
