### ISSUE TITLE
Text copy update to ' How it Works' section

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#91]
![howitworks](https://user-images.githubusercontent.com/29130378/108390406-7d52b380-71c5-11eb-8dea-efc665cbeb2a.png)

Replace copy with : 
Commit provides the space for Software Engineers to build relationships, experience growth at their own pace and establish a deeper network. We hire remote-first Engineers who want to eliminate the risk and the friction of finding and working for startups in Silicon Valley.  

Commit Engineers are matched with startup projects on a three month basis, and if there is a fit with the startup, we facilitate the transition to full time at that company. Otherwise, there is no obligation to join and you can get matched with a new startup instead.

While at Commit, we provide coaching opportunities, professional development and internal projects to help develop our own open source platforms. 

Even after Commit Engineers ‘graduate’ to startups, they remain a member of the Community so they can continue to tap into the knowledge base and join craft, skills or interest based groups

**Comment by adriandelisle** [comment]
Done in #98
