### ISSUE TITLE
Make company logo sizes larger

### ISSUE THREAD

**Issue by anikey** [commitdev/commit.dev-proto#92]
![companies](https://user-images.githubusercontent.com/29130378/108390676-c30f7c00-71c5-11eb-84ba-d91a9e55ead5.png)

Please refer to figma design
https://www.figma.com/file/YxruXOcQhx8dQW0h9REOQ4/commit_website?node-id=1202%3A1125

**Comment by adriandelisle** [comment]
Done in #99
