### ISSUE TITLE
Mobile Nav from Home -> About results in blank page.

### ISSUE THREAD

**Issue by adriandelisle** [commitdev/commit.dev-proto#93]
Steps to recreate:

1.  Go to https://launch.commit-staging.dev/
2.  Resize screen to <576px
2. Open the hamburger menu
3. Click on `About`

Expected result:
You're taken to the `About` page

Actual result:
A blank page is shown

Media:
![Kapture 2021-02-18 at 09 55 23](https://user-images.githubusercontent.com/10035832/108400336-f22aeb00-71cf-11eb-81cf-83080c9fa9a0.gif)

**Comment by DjordjeVujatovic** [comment]
Issue resolved in this PR: https://github.com/commitdev/commit.dev/pull/100
